# Generated by Django 5.2 on 2025-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Телеграмм ID",
            ),
        ),
    ]
