# Generated by Django 5.2 on 2025-04-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_city_user_tg_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="tg_id",
            new_name="tg_chat_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
