volumes:
  pg_data:
  static_volume:
  media_volume:
  redis_data:

services:
  db:
    container_name: pg_db_prod
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: ivenauto/atomic_habits
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
#    ports:
#      - 8000:8000
    restart: unless-stopped


  gateway:
    container_name: nginx
    image: nginx:1.23
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    container_name: ah_redis_prod
    image: redis:7
    volumes:
      - redis_data:/data
    restart: unless-stopped