volumes:
  postgres_data:
  static:

networks:
  atomic_habits_network:
    driver: bridge

services:
  db:
    container_name: ah_db
    networks:
      - atomic_habits_network
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: ah_backend
    networks:
      - atomic_habits_network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static:/backend_static
    expose:
      - "8000"
    depends_on:
      - db
      - redis


  redis:
    container_name: ah_redis
    networks:
      - atomic_habits_network
    image: redis:7
    restart: always

  celery:
    container_name: ah_celery
    networks:
      - atomic_habits_network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    command: >
      celery -A config worker -l INFO ${CELERY_OPTIONS}
    restart: always

  celery_beat:
    container_name: ah_celery_beat
    networks:
      - atomic_habits_network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    command: celery -A config beat -l INFO
    restart: always

  nginx:
    container_name: ah_proxy
    networks:
      - atomic_habits_network
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - static:/staticfiles/
    depends_on:
      - backend