volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  backend:
    container_name: ah_backend
    image: ivenauto/atomic_habits
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media