# Generated by Django 5.2 on 2025-04-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество выполнений привычки в неделю",
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
