# Generated by Django 5.2 on 2025-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                help_text="Введите время на выполнение в секундах.",
                verbose_name="Время на выполнение в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Периодичность выполнения привычки в днях",
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
