# Generated by Django 5.2 on 2025-04-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "habits",
            "0003_alter_habit_estimated_duration_alter_habit_frequency",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Может быть только приятной (is_pleasant_habit: True)",
                limit_choices_to={"is_pleasant_habit": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
