# Generated by Django 5.2 on 2025-04-26 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_related_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                help_text="Введите время на выполнение в секундах.",
                validators=[
                    django.core.validators.MaxValueValidator(
                        120, "Время выполнения не должно превышать 120 секунд."
                    )
                ],
                verbose_name="Время на выполнение в секундах",
            ),
        ),
    ]
