# Generated by Django 5.2 on 2025-04-26 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_options_alter_habit_estimated_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                help_text="через сколько дней следует выполнять привычку",
                validators=[
                    django.core.validators.MaxValueValidator(
                        7,
                        "Привычку следует выполнять как минимум 1 раз в 7 дней.",
                    )
                ],
                verbose_name="Периодичность выполнения в днях",
            ),
        ),
    ]
